[[main]]
none = "none"

[[main]]
name = "Instruments"
pageRef = "instruments"
identifier = "e2MTZEkyRQ"
weight = 9999

[[main]]
name = "Medias"
url = "https://soundcloud.com/takotp"
identifier = "6BaVWw0XgQ"
weight = 20

[[footer]]
none = "none"
