[[main]]
none = "none"

[[main]]
name = "Instruments"
pageRef = "instruments"
identifier = "e2MTZEkyRQ"
weight = 1

[[main]]
name = "Medias"
pageRef = "medias"
externalUrl = "https://soundcloud.com/takotp"
identifier = "6BaVWw0XgQ"
weight = 2

[[footer]]
none = "none"
