[[main]]
none = "none"

[[main]]
name = "Instruments"
pageRef = "instruments"
identifier = "yLlrw5T7Rd"
weight = 2

[[main]]
name = "Medias"
url = "https://soundcloud.com/takotp"
identifier = "6BaVWw0XgQ"
weight = 1
none = "none"

[[footer]]
none = "none"
