[[main]]
none = "none"

[[main]]
name = "Instruments"
pageRef = "instruments"
identifier = "e2MTZEkyRQ"
weight = 9999

[[main]]
name = "Medias"
pageRef = "medias"
identifier = "6BaVWw0XgQ"
weight = 9999

[[footer]]
none = "none"
