[[main]]
none = "none"

[[main]]
name = "Instruments"
pageRef = "instruments"
identifier = "yLlrw5T7Rd"
weight = 1

[[main]]
name = "Medias"
url = "https://soundcloud.com/takotp"
identifier = "6BaVWw0XgQ"
weight = 2
none = "none"

[[footer]]
none = "none"

[[footer]]
name = "Contacts"
pageRef = "https://instagram.com/tako.tp/"
identifier = "KTOQF5xbbV"
weight = 9999
